name: Backup ZIP

on:
  schedule:
    - cron: "0 3 1 * *"   # Cada dia 1 a les 03:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create dated ZIP
        run: |
          rm -rf .git
          DATE=$(date +'%Y-%m-%d_%H-%M-%S')
          zip -r "sentinella_backup_$DATE.zip" .

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentinella-backup
          path: sentinella_backup_*.zip
